# Generated by Django 6.0.1 on 2026-01-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DriveX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], default='car', max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('seating_capacity', models.IntegerField(default=4)),
                ('model_year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('rc_book', models.FileField(blank=True, null=True, upload_to='vehicles/docs/')),
                ('insurance', models.FileField(blank=True, null=True, upload_to='vehicles/docs/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='DriveX.userprofile')),
            ],
        ),
    ]
