# Generated by Django 6.0.1 on 2026-01-28 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('renter', 'Renter'), ('owner', 'Car Owner')], default='renter', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('aadhaar_image', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('license_type', models.CharField(blank=True, choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler')], max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=20)),
                ('license_image', models.FileField(blank=True, null=True, upload_to='documents/license/')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='users/qr/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
